language: node_js
sudo: false
node_js:
- 8
script:
- npm run ci
- chmod 777 ./test/shell_scripts/run_tests.sh
#- ./test/shell_scripts/run_tests.sh

deploy:
  provider: npm
  email: pearson-design-accelerator@pearson.com
  api_key:
    secure: travis/encrypted/deploykey
  skip_cleanup: true
  on:
    branch: master
    tags: true
env:
  global:
    secure: travis/encrypted/qakey
